language: python
python:
  - "2.7"
install:
  - pip install -U -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov
  - pip install .
script: py.test --cov=ta4
after_success: coveralls
